import {useEffect, useState} from "react";
import styles from "./actionPanel.module.css";
import GameState from "../../GameState";
import { observer } from 'mobx-react-lite';
import { Scrollbar } from "react-scrollbars-custom";
import { Loader } from "../commons/Loader";
import {useParams} from "react-router-dom";

export const AnalysisPanel = observer(({ onClose }) => {
    let { id } = useParams();
    const [isLoading, setIsLoading] = useState(false);
    const [gameAnalysis, setGameAnalysis] = useState([]);
    const [game, setGame] = useState([]);

    let dataGame = {
        fen: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
        idGame: id,
        depth: 12,
        //pgn: "1. e4 e5 2. Nf3 Nc6 3. Bb5 d6 "
    };

    useEffect(() => {
        setIsLoading(true);

        fetch("http://localhost:5000/api/getgame", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            credentials: "include",
            body: JSON.stringify(dataGame),
        })
            .then((response) => {
                if (!response.ok) {
                    throw new Error(response.statusText);
                }
                return response.json();
            })
            .then((payload) => {
                setGame(payload);
                console.log("payload: ", payload);

                let gameUser = {
                    fen: "r1bq1rk1/p1ppbppp/p1n2n2/4p3/4P3/3P1N2/PPP2PPP/RNBQ1RK1 w - - 0 7",
                    depth: 12,
                    pgn: payload[0].pgn
                }
                let history = gameUser.pgn;
                //GameState.history = JSON.parse(history);
                /*
                let historyRecord = {
                    figure: figures[start].ascii,
                    start,
                    end,
                    captured: null,
                    castling: null,
                  };
                 */
                console.log("gameUser: ", gameUser);

                fetch("http://localhost:5000/api/sendposition", {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json",
                    },
                    credentials: "include",
                    body: JSON.stringify(gameUser),
                })
                    .then((response) => {
                        if (!response.ok) {
                            throw new Error(response.statusText);
                        }
                        return response.json();
                    })
                    .then((payload2) => {
                        setGameAnalysis(payload2);
                        console.log("payload: ", payload2);
                    })
                    .catch((e) => {
                        console.log(e);
                    })
                    .finally(() => {
                        setIsLoading(false);
                    });
            })
            .catch((e) => {
                console.log(e);
            })
            .finally(() => {
                console.log("finallyGame")
            });

    }, []);

  GameState.isAnalysis = true;

  /*
  {gameAnalysis.conslusion.map((gameConslusion) => (
              <div>
                  {gameConslusion}
              </div>
          ))}
   */

  return (
    <div className={styles.actionPanel}>
      <Scrollbar style={{ width: "103%", height: "100%" }}>
          {isLoading && <Loader />}
          Анализ
          <p>ходы были неплохими</p>
          <p>а ход e4 был вообще отличный</p>
          <p>webpack finds all relative module references in CSS (they start with ./) and replaces them with the final paths from the compiled bundle. If you make a typo or accidentally delete an important file, you will see a compilation error, like when you import a non-existent JavaScript module. The final filenames in the compiled bundle are generated by webpack from content hashes. If the file content changes in the future, webpack will give it a different name in production so you don’t need to worry about long-term caching of assets.

              Please be advised that this is also a custom feature of webpack.

              It is not required for React but many people enjoy it (and React Native uses a similar mechanism for images).

              An alternative way of handling static assets is described in the next section.
              webpack finds all relative module references in CSS (they start with ./) and replaces them with the final paths from the compiled bundle. If you make a typo or accidentally delete an important file, you will see a compilation error, like when you import a non-existent JavaScript module. The final filenames in the compiled bundle are generated by webpack from content hashes. If the file content changes in the future, webpack will give it a different name in production so you don’t need to worry about long-term caching of assets.

              Please be advised that this is also a custom feature of webpack.

              It is not required for React but many people enjoy it (and React Native uses a similar mechanism for images).

              An alternative way of handling static assets is described in the next section.
              webpack finds all relative module references in CSS (they start with ./) and replaces them with the final paths from the compiled bundle. If you make a typo or accidentally delete an important file, you will see a compilation error, like when you import a non-existent JavaScript module. The final filenames in the compiled bundle are generated by webpack from content hashes. If the file content changes in the future, webpack will give it a different name in production so you don’t need to worry about long-term caching of assets.

              Please be advised that this is also a custom feature of webpack.

              It is not required for React but many people enjoy it (and React Native uses a similar mechanism for images).

              An alternative way of handling static assets is described in the next section.</p>
      </Scrollbar>
    </div>
  );
});
